services:
  db:
    image: mariadb:10.6.4-focal
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qwer@ASDF1
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=catalina
      - MYSQL_PASSWORD=qwer@ASDF1
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=catalina
      - WORDPRESS_DB_PASSWORD=qwer@ASDF1
      - WORDPRESS_DB_NAME=wordpress
volumes:
  db_data: